// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCy1voBg-VKh1JDyAzjR7uHo702j18FQo0',
    appId: '1:811735152100:web:218a72f1bf56e2587c83f1',
    messagingSenderId: '811735152100',
    projectId: 'noteapp-86f00',
    authDomain: 'noteapp-86f00.firebaseapp.com',
    databaseURL: 'https://noteapp-86f00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noteapp-86f00.appspot.com',
    measurementId: 'G-DH9LLDBP98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz4wOEg4XdZ9jqbd6bmMF0wCyYgPH3870',
    appId: '1:811735152100:android:2f9f6c20abf50eb77c83f1',
    messagingSenderId: '811735152100',
    projectId: 'noteapp-86f00',
    databaseURL: 'https://noteapp-86f00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noteapp-86f00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpPEh6GMBNWp6u1RL4LDaEFZFefBXfbPw',
    appId: '1:811735152100:ios:d555d16bf0b33b6a7c83f1',
    messagingSenderId: '811735152100',
    projectId: 'noteapp-86f00',
    databaseURL: 'https://noteapp-86f00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noteapp-86f00.appspot.com',
    androidClientId: '811735152100-m2c1a1c49ip7a9tmhs7o0hmme4vohomk.apps.googleusercontent.com',
    iosClientId: '811735152100-i4s9aomjdgbahe7msaotcafg4s3nlorq.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpPEh6GMBNWp6u1RL4LDaEFZFefBXfbPw',
    appId: '1:811735152100:ios:d555d16bf0b33b6a7c83f1',
    messagingSenderId: '811735152100',
    projectId: 'noteapp-86f00',
    databaseURL: 'https://noteapp-86f00-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noteapp-86f00.appspot.com',
    androidClientId: '811735152100-m2c1a1c49ip7a9tmhs7o0hmme4vohomk.apps.googleusercontent.com',
    iosClientId: '811735152100-i4s9aomjdgbahe7msaotcafg4s3nlorq.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteApp',
  );
}
